import { useEffect, useState, type ReactNode } from 'react'
import { ArrowLeft, ArrowUpRight, Menu, Moon, Sun, X } from 'lucide-react'
import { createRoot } from 'react-dom/client'
import { Architecture } from './components/Architecture'
import { profile } from './data/portfolio'
import './styles.css'
import './additions.css'
import './site.css'

const notes = [
  ['Understanding Spark Partitions', 'A practical explanation of partitions, tasks, stages, and shuffle.'],
  ['Designing Incremental ETL Pipelines', 'Watermarks, idempotency, and incremental processing patterns.'],
  ['Why Redshift COPY Is Faster Than Row-Level Inserts', 'Understanding bulk warehouse ingestion.'],
  ['Airflow DAG Design Patterns', 'Dependencies, retries, branching, and scheduling.'],
  ['SCD Type 1 vs Type 2', 'Practical implementation patterns for dimensional data.'],
]
const navigate = (path: string) => { history.pushState({}, '', path); dispatchEvent(new PopStateEvent('popstate')) }
function Link({ to, children, className = '' }: { to: string; children: ReactNode; className?: string }) { return <a className={className} href={to} onClick={e => { if (to.startsWith('/')) { e.preventDefault(); navigate(to) } }}>{children}</a> }
function Layout({ children }: { children: ReactNode }) { const [open, setOpen] = useState(false); const [light, setLight] = useState(false); useEffect(() => { document.documentElement.dataset.theme = light ? 'light' : 'dark' }, [light]); return <><header className="journal-nav"><nav><Link to="/" className="journal-brand">Abinav.</Link><button className="journal-menu" onClick={() => setOpen(!open)} aria-label="Open menu">{open ? <X size={18}/> : <Menu size={19}/>}</button><div className={`journal-links ${open ? 'open' : ''}`}>{[['/work','Work'],['/projects','Projects'],['/notes','Notes'],['/about','About'],['/contact','Contact']].map(([to,label]) => <Link key={to} to={to}>{label}</Link>)}<button className="theme-toggle" onClick={() => setLight(!light)} aria-label="Toggle theme">{light ? <Moon size={15}/> : <Sun size={15}/>}</button></div></nav></header><main className="journal-main">{children}</main><footer className="journal-footer">You made it to the bottom. © 2026 Abinav</footer></> }
function Label({ children }: { children: ReactNode }) { return <h2 className="journal-label"><span>—</span>{children}</h2> }
function Back() { return <Link to="/" className="back"><ArrowLeft size={15}/> Home</Link> }
function Home() { return <Layout><section className="journal-hero"><p>Hello, I’m</p><h1>Abinav S.</h1><h2>Data Engineer building production data systems.</h2><p className="journal-subtitle">Designing and developing reliable ETL pipelines, cloud data platforms, and data workflows using Python, SQL, AWS, Apache Airflow, and PySpark.</p></section><section className="journal-section"><Label>Work experience</Label><div className="compact-list"><Link to="/work"><div><strong>Virtusa</strong><span>Associate Software Engineer — Data Engineering</span><p>Designing and developing AWS-based production ETL pipelines and cloud data workflows for a financial data platform.</p></div><time>Jan 2024 – Present</time></Link><Link to="/work"><div><strong>Virtusa</strong><span>Software Engineering Intern — Data Engineering</span><p>Developed ETL workflows using Python, SQL, Airflow, AWS, and Docker.</p></div><time>Jan 2023 – Apr 2023</time></Link></div></section><section className="journal-section"><Label>Recent notes</Label><div className="note-list">{notes.slice(0,4).map(([title, description]) => <Link to="/notes" key={title}><div><strong>{title}</strong><p>{description}</p></div><time>Coming soon</time></Link>)}</div></section><section className="journal-section little-more"><Label>A little more</Label><p>I build data pipelines, learn how systems work, and write down what I learn along the way.</p><p>Currently focused on data engineering, distributed processing, cloud data platforms, and reliable production systems.</p><div className="journal-socials"><a href={profile.github} target="_blank" rel="noreferrer">GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href={`mailto:${profile.email}`}>Email</a></div></section></Layout> }
const achievements = ['Designed and developed production batch ETL pipelines processing 5M+ financial records daily with a 99.9% success rate.','Built end-to-end workflows spanning ingestion, transformation, validation, orchestration, and downstream delivery.','Designed layered Redshift architecture (L1 raw → L2 reporting), improving query performance by 40%.','Engineered Airflow DAGs with business-day logic, branching, dependencies, retries, and scheduling across 150+ workflows.','Tuned Redshift COPY-based ingestion for 3× faster loads.','Implemented automated data validation reducing recurring data issues by 25%.','Developed SQL deduplication and incremental-load transformations.','Integrated S3, Glue, Lambda, Redshift, IAM, CloudWatch, and SNS.']
function Work() { return <Layout><header className="page-intro"><Back/><p>Work</p><h1>Building data systems that hold up in production.</h1></header><section className="detail-block"><div className="detail-head"><div><h2>Virtusa</h2><p>Associate Software Engineer — Data Engineering</p></div><time>Jan 2024 – Present</time></div><p className="detail-lead">Designing and developing AWS-based batch data pipelines for a financial data platform.</p><ul>{achievements.map(item => <li key={item}>{item}</li>)}</ul><div className="ownership"><b>Production ownership</b><p>After the development transition in June 2026, assumed offshore L3 ownership of the platform, driving critical issue resolution, pipeline recovery, upstream dependency coordination, and downstream data validation.</p></div></section><section className="detail-block secondary-detail"><div className="detail-head"><div><h2>Virtusa</h2><p>Software Engineering Intern — Data Engineering</p></div><time>Jan 2023 – Apr 2023</time></div><p>Developed POC ETL workflows using Python and SQL, Airflow dependencies and retries, AWS S3 and Lambda, and Docker-based pipeline environments.</p></section><section className="small-detail"><Label>Toolkit</Label><p>Python · SQL · PySpark · AWS · Apache Airflow · AWS Glue · Redshift · Snowflake · dbt · Docker · PostgreSQL · Pandas · Databricks</p></section></Layout> }
function Projects() { return <Layout><header className="page-intro"><Back/><p>Projects</p><h1>Selected data engineering work.</h1></header><Link to="/projects/retail-sales-lakehouse" className="project-listing"><p>Flagship project</p><h2>Retail Sales Lakehouse <ArrowUpRight size={20}/></h2><span>End-to-End Incremental Batch Data Pipeline</span><div>An end-to-end batch data platform demonstrating incremental ingestion, distributed processing, cloud warehousing, dimensional modeling, and automated data quality validation.</div></Link></Layout> }
function ProjectDetail() { const decisions = [['Why incremental loads?','Avoid reprocessing unchanged transactional data and reduce unnecessary pipeline work.'],['Why watermarking?','Track the last successfully processed point to support reliable incremental extraction.'],['Why Bronze / Silver layers?','Separate raw ingestion from business transformations, making pipelines easier to validate, rerun, and maintain.'],['Why Parquet partitioning?','Organize data by processing date and reduce unnecessary data scanning.']]; return <Layout><header className="page-intro"><Back/><p>Projects / Retail Sales Lakehouse</p><h1>Retail Sales Lakehouse.</h1><span>End-to-End Incremental Batch Data Pipeline</span></header><section className="project-overview"><Label>Overview</Label><p>An end-to-end batch data platform demonstrating incremental ingestion, distributed processing, cloud warehousing, dimensional modeling, and automated data quality validation.</p></section><section className="project-architecture"><Label>Architecture</Label><Architecture /></section><section className="decision-block"><Label>Engineering decisions</Label><div>{decisions.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="implementation"><Label>Implementation</Label><div><p><b>Ingestion & orchestration.</b> Dependency-driven Airflow workflows coordinate full and incremental ingestion using watermark extraction, batch-date partitioning, runtime parameters, and idempotent processing.</p><p><b>Processing & quality.</b> Six parallel Bronze ingestion jobs feed PySpark transformations for schema enforcement, window-based deduplication, FX reference-data enrichment, derived metrics, and reject handling.</p><p><b>Warehousing & models.</b> Partitioned Parquet zones load to Snowflake through stages and COPY INTO. dbt produces staging, dimension, fact, and analytical models with surrogate keys, latest-record handling, and automated tests.</p></div><a className="journal-button" href={profile.github} target="_blank" rel="noreferrer">View GitHub <ArrowUpRight size={15}/></a></section></Layout> }
function Notes() { return <Layout><header className="page-intro"><Back/><p>Notes</p><h1>Things I’m learning about data systems.</h1></header><div className="note-list all-notes">{notes.map(([title,description]) => <article key={title}><div><h2>{title}</h2><p>{description}</p></div><time>Coming soon</time></article>)}</div></Layout> }
function About() { return <Layout><header className="page-intro"><Back/><p>About</p><h1>Data Engineer based in Chennai, India.</h1></header><section className="about-copy"><p>I build and operate production data pipelines for financial data, working across ingestion, transformation, orchestration, validation, and data warehousing.</p><p>At Virtusa, I work with S3, Glue, Lambda, Redshift, CloudWatch, Python, SQL, and Apache Airflow. More recently, I have also taken offshore L3 ownership of the platform.</p></section><section className="small-detail"><Label>Skills</Label><p>Python · SQL · AWS · Apache Airflow · PySpark · AWS Glue · Amazon Redshift · S3 · Lambda · Snowflake · dbt · Docker · PostgreSQL · Pandas · Databricks</p></section><section className="credentials"><Label>Certifications</Label><p>AWS Certified Data Engineer – Associate <span>2024</span></p><p>AWS Certified AI Practitioner <span>2025</span></p><p>AWS Certified Solutions Architect – Associate <span>2023</span></p></section><section className="credentials"><Label>Education</Label><p><b>Sri Ramakrishna Engineering College</b><span>May 2023</span></p><p>B.E. Computer Science · CGPA 8.0</p></section></Layout> }
function Contact() { return <Layout><header className="page-intro contact-page"><Back/><p>Contact</p><h1>Interested in building reliable data systems?</h1><div className="contact-list"><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={`tel:${profile.phone.replace(/\s/g,'')}`}>{profile.phone}</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a></div></header></Layout> }
function App() { const [path, setPath] = useState(location.pathname); useEffect(() => { const onPop = () => setPath(location.pathname); addEventListener('popstate', onPop); return () => removeEventListener('popstate', onPop) }, []); if (path === '/work') return <Work/>; if (path === '/projects') return <Projects/>; if (path === '/projects/retail-sales-lakehouse') return <ProjectDetail/>; if (path === '/notes') return <Notes/>; if (path === '/about') return <About/>; if (path === '/contact') return <Contact/>; return <Home/> }
createRoot(document.getElementById('root')!).render(<App />)
